vel_limit_mps:            1.000000
accel_limit_mps2:         0.500000
decel_limit_mps2:         0.500000
dtz_decel_limit_mps2:     1.000000
yaw_rate_limit_rps:       1.000000
yaw_accel_limit_rps2:     1.000000
lateral_accel_limit_mps2: 4.905000
tire_rolling_diameter_m:  0.254
wheel_base_length_m:      0.693
wheel_track_width_m:      0.693
gear_ratio:               24.266700
enable_audio:             1
motion_while_charging:    0
balance_mode_enabled:     0
balace_gains:             0
vel_ctl_input_filter:     0
yaw_ctl_input_filter:     0

