<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      rmp.urdf.xacro
\authors   Matt Harding, Patrick Hussey
\copyright Copyright (c) 2015, Stanley Innovation, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Stanley Innovation nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot name="segway_robot" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:arg name="gpu" default="false"/>
    <xacro:property name="gpu" value="$(arg gpu)" />
    

    <!-- Included URDF/XACRO Files -->
    <xacro:include filename="$(find segway_description)/urdf/segway_components/battery.urdf.xacro" />
    <xacro:include filename="$(find segway_description)/urdf/segway_components/i2_wheel.urdf.xacro" />
    <xacro:include filename="$(find segway_description)/urdf/segway_components/std_gearbox_chassis.urdf.xacro" />
    <xacro:include filename="$(find segway_description)/urdf/segway_components/caster_assembly.urdf.xacro" />
    <xacro:include filename="$(find segway_description)/urdf/segway_components/single_spacer.urdf.xacro" />
    <xacro:include filename="$(find segway_description)/urdf/segway_components/payload_mount.urdf.xacro" />
    <xacro:include filename="$(find segway_description)/urdf/segway_components/ui_box.urdf.xacro" />
    <xacro:include filename="$(find segway_description)/urdf/accessories.urdf.xacro" />
    <!----> <xacro:include filename="$(find widowx_turret_description)/urdf/widowx_turret.urdf.xacro"/>  

    <xacro:property name="M_PI" value="3.14159"/>
    
    <!-- Wheel Mounting Positions -->
    <xacro:property name="track" value="0.542391" />
    <xacro:property name="wheel_vertical_offset" value="0.08255015" />

    <!-- Wheel Properties -->
    <xacro:property name="wheel_length" value="0.09224900" />
    <xacro:property name="wheel_radius" value="0.2405681" />

    <xacro:macro name="segway_robot">
        <gazebo> 
          <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"> 
              <robotNamespace>/</robotNamespace>
          </plugin> 
        </gazebo>
        
        <!-- Base link is the center of the robot's chassis between the motors projected on the ground -->
        <link name="base_link"/>
        
        <!--Chassis -->
        <xacro:std_gearbox_chassis chassis_prefix="base" parent="base_link">
            <origin xyz="0 0 ${-wheel_vertical_offset + wheel_radius}" rpy="0 0 0" />
        </xacro:std_gearbox_chassis>
        
        <link name="inertial_collision_link">
			<inertial>
				<mass value="58.216824" />
				<origin xyz="-0.002452 0.000023 0.23120" />
				<inertia ixx="5.441713"  ixy="0.017871" ixz="-0.023004"
                         iyx="0.017871"  iyy="4.732620" iyz="-0.000290"
                         izx="-0.023004" izy="-0.000290" izz="1.951671" />
			</inertial>
            <collision>
				<geometry>
					<mesh filename="package://segway_description/meshes/collision/RMP220_chassis_collision.stl" />
				</geometry>
			</collision>
		</link>
		
		<joint name="inertial_collision_joint" type="fixed" >
		    <parent link="base_chassis_link" />
		    <child link="inertial_collision_link" />
		</joint>
        
        <!--Gearbox Spacers -->
        <xacro:single_spacer spacer_prefix="left" parent="base_chassis_link">
            <origin xyz="0 0.19582 0.00665015" rpy="0 0 0" />
        </xacro:single_spacer>
        <xacro:single_spacer spacer_prefix="right" parent="base_chassis_link">
            <origin xyz="0 -0.19582 0.00665015" rpy="0 0 ${M_PI}" />
        </xacro:single_spacer>         

        <!-- Propulsion Batteries -->
        <xacro:battery battery_prefix="mcu_1" parent="base_chassis_link">
            <origin xyz="-0.09298 0 0" rpy="0 0 0" />
        </xacro:battery>

        <xacro:battery battery_prefix="mcu_0" parent="base_chassis_link">
            <origin xyz="0.09298 0 0" rpy="0 0 ${M_PI}" />
        </xacro:battery>

        <!-- Payload Mount -->
        <xacro:payload_mount parent="base_chassis_link">
            <origin xyz="0 0 0.60672" rpy="0 0 0" />
        </xacro:payload_mount>
        <!-- UI Box -->
        <xacro:ui_box parent="base_chassis_link">
            <origin xyz="0 0 0.45750" rpy="0 0 0" />
        </xacro:ui_box>

        <!-- UI Batteries -->
        <xacro:battery battery_prefix="aux" parent="base_chassis_link">
            <origin xyz="0.02315 0 0.52348" rpy="${M_PI} 0 0" />
        </xacro:battery>

        <!-- Segway wheel macros -->
        <xacro:i2_wheel wheel_prefix="left" parent="base_chassis_link" visual_rotation="0.0">
            <origin xyz="0 ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        </xacro:i2_wheel>
        <xacro:i2_wheel wheel_prefix="right" parent="base_chassis_link" visual_rotation="${M_PI}">
            <origin xyz="0 ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        </xacro:i2_wheel>
        
        <!-- Segway Caster Assembly-->
        <xacro:if value="$(optenv SEGWAY_HAS_REAR_CASTER false)">
            <xacro:caster_assembly caster_prefix="rear" parent="base_chassis_link">
                <origin xyz="-0.31472057 0 0.02425235" rpy="0 0 0" />
            </xacro:caster_assembly>
        </xacro:if>

        <xacro:if value="$(optenv SEGWAY_HAS_FRONT_CASTER false)">
            <xacro:caster_assembly caster_prefix="front" parent="base_chassis_link">
                <origin xyz="0.31472057 0 0.02425235" rpy="0 0 ${M_PI}" />
            </xacro:caster_assembly>
        </xacro:if>
 
        <!-- Segway BSA Link (sign convention applied at embedded level)-->
        <link name="bsa_link"/>
        <joint name="bsa_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="$(optenv SEGWAY_PARENT_LINK base_chassis_link)" />
            <child link="bsa_link" />
        </joint>
        <gazebo reference="bsa_link"/>
        
        <!-- Setup any accessories defined in the environment -->
        <xacro:segway_accessories />
    

    <!-- # ARA PARCA ###################################################################################### -->
    <link
    name="ara_parca_link">
    <inertial>
      <origin
        xyz="0 1.0588621593521E-17 -0.0578639244522826"
        rpy="0 0 0" />
      <mass
        value="1.34982525666118" />
      <inertia
        ixx="0.00281891394775808"
        ixy="4.74338450462408E-20"
        ixz="-1.00425720957971E-19"
        iyy="0.00281891394775808"
        iyz="4.93059029226279E-20"
        izz="0.00262460867965498" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://robot/meshes/ara_parca_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://robot/meshes/ara_parca_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="ara_parca_joint"
    type="fixed">
    <origin
      xyz="0 0.08 -0.15"
      rpy="0 0 -0.011591" />
    <parent
      link="base_chassis_link" />
    <child
      link="ara_parca_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  
  <!-- # PAN_TILT ###################################################################################### -->
	<xacro:widowx_turret parent="ara_parca_link" prefix="">
		<origin xyz="0 -0.075 0.87" rpy="0.0 0.0 1.54"/>
	</xacro:widowx_turret>

  <!-- # KAFA ###################################################################################### -->
  <link
    name="kafa_link">
    <inertial>
      <origin
        xyz="0.18065 -0.034976 -0.015996"
        rpy="0 0 1.54" />
      <mass
        value="1.98095" />
      <inertia
        ixx="0.0086192"
        ixy="-4.0365E-07"
        ixz="0.00068816"
        iyy="0.0073775"
        iyz="1.5958E-09"
        izz="0.0082719" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://robot/meshes/kafa_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.75294 0.75294 0.75294 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://robot/meshes/kafa_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="kafa_joint"
    type="fixed">
    <origin
      xyz="0 0.025 -1.038"
      rpy="0.0094676 0 0" />
    <parent
      link="top_plate_link" /> 
    <child
      link="kafa_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  <!-- # KABUK ######################################################################################  -->
  <link
    name="kabuk_link">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="0" />
      <inertia
        ixx="0"
        ixy="0"
        ixz="0"
        iyy="0"
        iyz="0"
        izz="0" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://robot/meshes/kabuk_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://robot/meshes/kabuk_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="kabuk_joint"
    type="fixed">
    <origin
      xyz="0 0 -0.15"
      rpy="0 0 1.54" />
    <parent
      link="base_chassis_link" />
    <child
      link="kabuk_link" />
    <axis
      xyz="0 0 0" />
  </joint>



  <!-- # VDL-16 ######################################################################################  -->
  <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
  <xacro:VLP-16 parent="kafa_link" name="velodyne" topic="/velodyne_points" hz="10" samples="1024" gpu="${gpu}">
    <origin xyz="-0.005 0.02 1.245" rpy="0.07 0 -1.57" />
  </xacro:VLP-16>
<!--
    <gazebo reference="velodyne">
    <material>Gazebo/FlatBlack</material>
    <sensor type="ray" name="lds_lfcd_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>False</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>1024</samples>
            <resolution>1</resolution>
            <min_angle>0.0</min_angle>
            <max_angle>6.28319</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>10</max>
          <resolution>0.015</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_lds_lfcd_controller" filename="libgazebo_ros_laser.so">
        <topicName>scan</topicName>
        <frameName>velodyne</frameName>
      </plugin>
    </sensor> 
  </gazebo> -->



  <!-- # ZED ###################################################################################### -->
   <xacro:include filename="$(find zed_description)/urdf/zed_descr.urdf.xacro"/>  
   <xacro:stereolabs_camera parent="kafa_link">
	 <origin xyz="-0.005 -0.067 1.225" rpy="3.14 3.06 1.62" />
   </xacro:stereolabs_camera>   
     
    </xacro:macro>

<gazebo>
  <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
    <alwaysOn>true</alwaysOn>
    <updateRate>50.0</updateRate>
    <bodyName>base_link</bodyName>
    <topicName>odom</topicName>
    <gaussianNoise>0.01</gaussianNoise>
    <frameName>world</frameName>
    <xyzOffsets>0 0 0</xyzOffsets>
    <rpyOffsets>0 0 0</rpyOffsets>
  </plugin>
</gazebo>

</robot>
