# http://wiki.ros.org/navfn
NavfnROS:
  allow_unknown:                true  #default: true
  planner_window_x:             0.0   #default: 0.0
  planner_window_y:             0.0   #default: 0.0
  default_tolerance:            0.1   #default: 0.0
  #visualize_potential:          false #default: false
  
# http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x:                    0.5     #default 2.5
  acc_lim_y:                    0.0     #default 2.5
  acc_lim_theta:                1.0     #default 3.2
  max_vel_x:                    1.0     #default 0.5
  min_vel_x:                    0.1     #default 0.1
  max_vel_theta:                1.0     #default 1.0
  min_vel_theta:                -1.0    #default -1.0
  min_in_place_vel_theta:       0.4     #default 0.4
  escape_vel:                   -0.1    #default -0.1
  holonomic_robot:              false   #default true

  # The following parameters are only used if holonomic_robot is set to true:
  # y_vels: [-0.3, -0.1, 0.1, 0.3] #default [-0.3, -0.1, 0.1, 0.3]

  # Goal Tolerance Parameters
  yaw_goal_tolerance:           0.1    #default 0.05
  xy_goal_tolerance:            0.2     #default 0.1
  latch_xy_goal_tolerance:      false   #default false

  # Forward Simulation Parameters
  sim_time:                     2.0     #default 1.0
  sim_granularity:              0.02    #default 0.025
  angular_sim_granularity:      0.02    #default 0.025
  vx_samples:                   6       #default 3
  vtheta_samples:               20      #default 10
  controller_frequency:         20.0    #default 20.0

  # Trajectory Scoring Parameters
  # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and
  # path_distance are expressed in units of meters or cells.
  meter_scoring:                true    #default false
  # The weighting for how much the controller should stay close to the path it was given
  pdist_scale:                  0.75     #default 0.6
  # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  gdist_scale:                  1.0      #default 0.8
  # The weighting for how much the controller should attempt to avoid obstacles.
  occdist_scale:                0.1     #default 0.01
  # How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_lookahead:            0.5     #default 0.325
  # Whether to score based on the robot's heading to the path or its distance from the path.
  heading_scoring:              false   #default false
  # How far to look ahead in time in seconds along the simulated trajectory when using heading scoring
  heading_scoring_timestep:     0.8     #default 0.8
  # Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout;
  # should be set to FALSE if using the Trajectory planner use DWA planner if you want DWA
  dwa:                          false   #default true
  # Whether to publish cost grid pointcloud; used for debugging and integration
  publish_cost_grid_pc:         false   #default false
  # Global frame of the planner
  global_frame_id:              /odom   #default odom

  # Oscillation Prevention Parameters
  # How far the robot must travel in meters before oscillation flags are reset
  oscillation_reset_dist:       0.25    #default 0.05

  # Global Plan Parameters
  prune_plan:                   true    #default true

DWAPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x:                    0.5     #default 2.5    
  acc_lim_y:                    0.0     #default 2.5
  acc_lim_th:                   1.0     #default 3.2
  max_trans_vel:                0.5     #default 0.55
  min_trans_vel:                0.1     #default 0.1
  max_vel_x:                    0.5     #default 0.55
  min_vel_x:                    -0.1    #default 0.0
  max_vel_y:                    0.0     #default 0.1
  min_vel_y:                    0.0     #default -0.1
  max_rot_vel:                  1.0     #default 1.0
  min_rot_vel:                  0.4     #default 0.4

  # Goal Tolerance Parameters
  yaw_goal_tolerance:           0.1     #default 0.05
  xy_goal_tolerance:            0.2     #default 0.1
  latch_xy_goal_tolerance:      false   #default false

  # Forward Simulation Parameters
  sim_time:                     2.0     #default 1.7
  sim_granularity:              0.02    #default 0.025
  angular_sim_granularity:      0.02    #default 0.025
  vx_samples:                   6       #default 3
  vtheta_samples:               20      #default 10
  controller_frequency:         20.0    #default 20.0
  penalize_negative_x:          true    #default true

  # Trajectory scoring parameters
  # The weighting for how much the controller should stay close to the path it was given
  path_distance_bias:             40.0    #default 32.0
  # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  goal_distance_bias:             30.0    #default 24.0
  # The weighting for how much the controller should attempt to avoid obstacles
  occdist_scale:                  0.1     #default 0.01
  # The distance from the center point of the robot to place an additional scoring point, in meters
  forward_point_distance:         0.5     #default 0.325
  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint,
  # in m/sop before a collision in order for a trajectory to be considered valid in seconds
  stop_time_buffer:               0.2     #default 0.2
  # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  scaling_speed:                  0.25    #default 0.25
  # The maximum factor to scale the robot's footprint by
  max_scaling_factor:             0.2     #default 0.2

  # Oscillation Prevention Parameters
  # How far the robot must travel in meters before oscillation flags are reset
  oscillation_reset_dist:       0.25    #default 0.05

  # Global Plan Parameters
  prune_plan:                   true    #default true

