explore_costmap:
  global_frame:              /map
  rolling_window:            false
  track_unknown_space:       true
  width:                     100.0
  height:                    100.0
  origin_x:                  -50.0
  origin_y:                  -50.0

  explore_boundary:
    resize_to_boundary:    true
    frontier_travel_point: closest

  plugins:
    - {name: explore_boundary,     type: "frontier_exploration::BoundedExploreLayer"}
    - {name: obstacles_costmap2d,  type: "costmap_2d::ObstacleLayer"}
    - {name: obstacles_voxel_grid, type: "costmap_2d::VoxelLayer"}
    - {name: inflation,            type: "costmap_2d::InflationLayer"}



