# 2D Costmap parameters
# http://www.ros.org/wiki/costmap_2d

### Coordinate frame and tf parameters ###
robot_base_frame:           segway/base_link
transform_tolerance:        0.5

# ---RMP220 footprint (Meters):---
footprint: [[0.525, 0.0], [0.524, 0.027], [0.522, 0.055], [0.519, 0.082], [0.514, 0.109], [0.507, 0.136], [0.499, 0.162], [0.49, 0.188], [0.48, 0.214], [0.468, 0.238], [0.455, 0.263], [0.44, 0.286], [0.425, 0.309], [0.408, 0.33], [0.39, 0.351], [0.371, 0.371], [0.351, 0.39], [0.33, 0.408], [0.309, 0.425], [-0.309, 0.425], [-0.33, 0.408], [-0.351, 0.39], [-0.371, 0.371], [-0.39, 0.351], [-0.408, 0.33], [-0.425, 0.309], [-0.44, 0.286], [-0.455, 0.262], [-0.468, 0.238], [-0.48, 0.214], [-0.49, 0.188], [-0.499, 0.162], [-0.507, 0.136], [-0.514, 0.109], [-0.519, 0.082], [-0.522, 0.055], [-0.524, 0.027], [-0.525, 0.0], [-0.524, -0.027], [-0.522, -0.055], [-0.519, -0.082], [-0.514, -0.109], [-0.507, -0.136], [-0.499, -0.162], [-0.49, -0.188], [-0.48, -0.214], [-0.468, -0.238], [-0.455, -0.263], [-0.44, -0.286], [-0.425, -0.309], [-0.408, -0.33], [-0.39, -0.351], [-0.371, -0.371], [-0.351, -0.39], [-0.33, -0.408], [-0.309, -0.425], [0.309, -0.425], [0.33, -0.408], [0.351, -0.39], [0.371, -0.371], [0.39, -0.351], [0.408, -0.33], [0.425, -0.309], [0.44, -0.286], [0.455, -0.262], [0.468, -0.238], [0.48, -0.214], [0.49, -0.188], [0.499, -0.162], [0.507, -0.136], [0.514, -0.109], [0.519, -0.082], [0.522, -0.055], [0.524, -0.027], [0.525, 0.0]]

# The following parameter is overwritten if the "footprint" parameter is set
#robot_radius:               0.325

### Costmap layer definitions ###
publish_frequency:           1.0
plugins:                     []

static:
  unknown_cost_value:        0
  lethal_cost_threshold:     100
  map_topic:                 map
  subscribe_to_updates:      true

obstacles_costmap2d:
  observation_sources: segway_scan
  segway_scan: {topic:                   segway/filtered_scan,
                data_type:               LaserScan,
                expected_update_rate:    0.5,
                observation_persistence: 0.0,
                marking:                 true,
                clearing:                true,
                inf_is_valid:            true,
                min_obstacle_height:     0.0,
                max_obstacle_height:     2.0,
                obstacle_range:          5.5,
                raytrace_range:          6.0}

obstacles_voxel_grid:
  origin_z:              0.0
  z_resolution:          0.2
  z_voxels:              10
  unknown_threshold:     5
  mark_threshold:        0
  publish_voxel_map:     false
  observation_sources: segway_point_cloud
  segway_point_cloud: {topic:                   segway/filtered_points2,
                       data_type:               PointCloud2,
                       expected_update_rate:    0.5,
                       observation_persistence: 0.0,
                       marking:                 true,
                       clearing:                true,
                       inf_is_valid:            false,
                       min_obstacle_height:     0.0,
                       max_obstacle_height:     2.0,
                       obstacle_range:          5.5,
                       raytrace_range:          6.0}

inflation:
  inflation_radius:           0.3  #default 0.5
  cost_scaling_factor:        10.0 #default 10.0

